### ISSUE TITLE
Input validation duplicate code

### ISSUE THREAD

**Issue by f-rakete** [kirannandedkar/SlotMachine#13]
https://github.com/kirannandedkar/SlotMachine/blob/f112b22a30723d1b2c76cd925eb33a201eaafa52/SlotMachine/Program.cs#L36-L60

the range check is implemented twice,  recommend simplifying that
```
     if (selectedOption > 8 || selectedOption <= 0) 
     { 
         isInputValid = false; 
     } 
```

**Comment by kirannandedkar** [comment]
I have fixed it
