### ISSUE TITLE
Nonsensical calculation in 0 lines won case

### ISSUE THREAD

**Issue by f-rakete** [kirannandedkar/SlotMachine#15]
https://github.com/kirannandedkar/SlotMachine/blob/f112b22a30723d1b2c76cd925eb33a201eaafa52/SlotMachine/Program.cs#L162-L171

line 169 🤔

**Comment by kirannandedkar** [comment]
@f-rakete  i didnt understood what is wrong

**Comment by f-rakete** [comment]
> @f-rakete  i didnt understood what is wrong

What's the intention with that line?
