### ISSUE TITLE
Repetitive checks could be done in a loop 

### ISSUE THREAD

**Issue by f-rakete** [kirannandedkar/SlotMachine#17]
https://github.com/kirannandedkar/SlotMachine/blob/f112b22a30723d1b2c76cd925eb33a201eaafa52/SlotMachine/Program.cs#L118-L150

**Comment by kirannandedkar** [comment]
@f-rakete can you help me here?

**Comment by f-rakete** [comment]
@kirannandedkar please formulate a proper question. See the how to ask questions video

**Comment by kirannandedkar** [comment]
i meant i didnt understood your question. Do you mean i should use another do while loop for this case @f-rakete ?

**Comment by kirannandedkar** [comment]
@f-rakete  can you also comment on this. Did you mean that i use one more loop for this?

**Comment by kirannandedkar** [comment]
wow completely makes sense. Done
