### ISSUE TITLE
Unnecessary ReadiLine in Case User selects option 8?

### ISSUE THREAD

**Issue by f-rakete** [kirannandedkar/SlotMachine#19]
https://github.com/kirannandedkar/SlotMachine/blob/d4cc01813ac4158b020f2dedbd5f6966571ec86d/SlotMachine/Program.cs#L43-L48

Please let me know what the purpose is here

**Comment by kirannandedkar** [comment]
@f-rakete  the purpose is that if user dont have enough credit to play all 8 lines then program should not exit and he should be allowed to play different line

**Comment by kirannandedkar** [comment]
@f-rakete what i way around then because i have to set isInputValid to false in both cases and i actually want to start them again. Getting bit lost

**Comment by f-rakete** [comment]
that seems fine, but please test your control flow here, debug it - you'll see what's going wrong here for sure  👍

**Comment by kirannandedkar** [comment]
@f-rakete just not able to avoid setting isInputValid to false.

**Comment by f-rakete** [comment]
> @f-rakete just not able to avoid setting isInputValid to false.

setting this to false is fine, but then you don't have to readline in that if branch - please run the flow trough the debugger to see what happens in that case, you'll be asked twice
