### ISSUE TITLE
Don't use a public static field for this

### ISSUE THREAD

**Issue by mayisa87** [kirannandedkar/SlotMachine#20]
https://github.com/kirannandedkar/SlotMachine/blob/4c449bb258bc43da7bc74bb6f03acadbf97b108e/SlotMachine/Program.cs#L7

At this stage no static fields are necessary accept for the Random object:
https://github.com/kirannandedkar/SlotMachine/blob/4c449bb258bc43da7bc74bb6f03acadbf97b108e/SlotMachine/Program.cs#L7

This can be define das public static readonly before Main.

A public static field is more or less like a constant, they are used for values that won't change anymore usually and in general should be used very rarely! Your TOTAL_CREDIT can be a usual variable inside the main. Instead of defining a static variable, you can define a constant  like STARTING_CREDIT = 10 and initialize your variable totalCredit in Main with this value.

**Comment by kirannandedkar** [comment]
Good point. Removed
