### ISSUE TITLE
Split up your methods in right class files!

### ISSUE THREAD

**Issue by mayisa87** [kirannandedkar/SlotMachine#22]
In this linked video on teachable, Florian describes how to split up your code into UI and Logic. The goal in the end should be to have one class holding all UI related methods and one class holding all that is related to Logic and Game.

https://course.raketementoring.com/courses/rakete-mentoring/lectures/45651272
https://course.raketementoring.com/courses/rakete-mentoring/lectures/45560459

Currently you got a compelte mixture in your Slotmatchine.cs

UI Methods:
https://github.com/kirannandedkar/SlotMachine/blob/4c449bb258bc43da7bc74bb6f03acadbf97b108e/SlotMachine/SlotMachine.cs#L11
https://github.com/kirannandedkar/SlotMachine/blob/4c449bb258bc43da7bc74bb6f03acadbf97b108e/SlotMachine/SlotMachine.cs#L24

Logic methods:
https://github.com/kirannandedkar/SlotMachine/blob/4c449bb258bc43da7bc74bb6f03acadbf97b108e/SlotMachine/SlotMachine.cs#L39
https://github.com/kirannandedkar/SlotMachine/blob/4c449bb258bc43da7bc74bb6f03acadbf97b108e/SlotMachine/SlotMachine.cs#L50
https://github.com/kirannandedkar/SlotMachine/blob/4c449bb258bc43da7bc74bb6f03acadbf97b108e/SlotMachine/SlotMachine.cs#L60
https://github.com/kirannandedkar/SlotMachine/blob/4c449bb258bc43da7bc74bb6f03acadbf97b108e/SlotMachine/SlotMachine.cs#L70

**Comment by kirannandedkar** [comment]
I agree
