### ISSUE TITLE
Define constants for your user inputs and a class file

### ISSUE THREAD

**Issue by mayisa87** [kirannandedkar/SlotMachine#23]
https://github.com/kirannandedkar/SlotMachine/blob/4c449bb258bc43da7bc74bb6f03acadbf97b108e/SlotMachine/Program.cs#L41

If you have some input values, like your different user choices, define whether an enum for it or at least constants!

As you are already in the middle of splitting code into class files,  you could move all of your constants into a separated file, called Constants.cs
In there you can define all of your constants as public. This make them accessable in all classfiles.

Like:
`public const USER_CHOICE_HORIZONTAL = 1;`

**Comment by kirannandedkar** [comment]
i am comparing with existing enum. Please let me know your thoughts
