### ISSUE TITLE
Validation - put into method

### ISSUE THREAD

**Issue by mayisa87** [kirannandedkar/SlotMachine#25]
![image](https://github.com/kirannandedkar/SlotMachine/assets/130921606/41313691-a1d4-46e5-859b-5ac01dfa5eaa)

In general, if you have  a bool like your isInputValid, it makes more sense to define it shortly before first usage. This makes the code easier to read. Just as general information.

You should anyway move your code into your UIMethods.cs (not yet existing, see issue #22), this while loop checking on input and do validation is a typical UI method.

**Comment by kirannandedkar** [comment]
Makes sense
