### ISSUE TITLE
Add a userBank or starting credits 

### ISSUE THREAD

**Issue by incredibleLeitman** [kirannandedkar/SlotMachine#9]
Currently the user can just continue playing even if loosing all the time and getting the moneyWon below 0.

I would recommend giving the user some starting credits where the bet gets deducted everytime he spins the wheel and in case of a win add the win money. If this user credits reaches 0 or the bet cannot be reduced the game should stop

**Comment by kirannandedkar** [comment]
sorry its solved as part of issue no 8. I wrongly tagged as issue no 8 but should have tagged as issue no 9 :(
